import os
import smtplib
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText

def send_email_alert(job, match_result, notion_url):
    sender_email = os.getenv("GMAIL_SENDER")
    sender_password = os.getenv("GMAIL_APP_PASSWORD")
    receiver_email = os.getenv("NOTIFICATION_RECEIVER")
    
    if not all([sender_email, sender_password, receiver_email]):
        print("Email credentials not fully configured in environment variables.")
        return False
        
    score = match_result.get("match_score", 0)
    
    msg = MIMEMultipart('alternative')
    msg['Subject'] = f"🚀 High Match Alert ({score}%): {job.get('title')} at {job.get('company')}"
    msg['From'] = sender_email
    msg['To'] = receiver_email
    
    html_content = f"""
    <html>
      <body style="font-family: Arial, sans-serif; line-height: 1.6; color: #333;">
        <div style="max-width: 600px; margin: 0 auto; border: 1px solid #ddd; border-radius: 8px; padding: 20px; box-shadow: 0 4px 8px rgba(0,0,0,0.1);">
          <h2 style="color: #2c3e50; border-bottom: 2px solid #3498db; padding-bottom: 10px;">{job.get('title')}</h2>
          <h3 style="color: #7f8c8d;">🏢 {job.get('company')}</h3>
          
          <div style="display: flex; gap: 20px; margin-top: 20px;">
            <div style="background-color: #f1f8ff; padding: 10px 20px; border-radius: 5px; border-left: 4px solid #3498db;">
              <strong style="font-size: 1.2em; color: #2980b9;">Score: {score}/100</strong>
            </div>
            <div style="background-color: #fdf2e9; padding: 10px 20px; border-radius: 5px; border-left: 4px solid #e67e22;">
              <strong>Missing Skills:</strong><br/>
              {", ".join(match_result.get('missing_skills', [])) or "None! 🎉"}
            </div>
          </div>
          
          <div style="margin-top: 30px; text-align: center;">
            <a href="{job.get('url')}" style="background-color: #2ecc71; color: white; padding: 12px 24px; text-decoration: none; border-radius: 5px; font-weight: bold; margin-right: 10px;">Apply Now</a>
            {f'<a href="{notion_url}" style="background-color: #95a5a6; color: white; padding: 12px 24px; text-decoration: none; border-radius: 5px; font-weight: bold;">View in Notion</a>' if notion_url else ''}
          </div>
          
          <p style="margin-top: 30px; font-size: 0.9em; color: #999;">
            This alert was automatically generated by your Job-Hunting Pipeline.
          </p>
        </div>
      </body>
    </html>
    """
    
    part = MIMEText(html_content, 'html')
    msg.attach(part)
    
    try:
        server = smtplib.SMTP('smtp.gmail.com', 587)
        server.starttls()
        server.login(sender_email, sender_password)
        server.send_message(msg)
        server.quit()
        return True
    except Exception as e:
        print(f"Failed to send email alert for job {job.get('job_id')}: {e}")
        return False
